/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as IndexImport } from './routes/index';
import { Route as StatusHashImport } from './routes/status.$hash';

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any);

const StatusHashRoute = StatusHashImport.update({
  id: '/status/$hash',
  path: '/status/$hash',
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    '/status/$hash': {
      id: '/status/$hash';
      path: '/status/$hash';
      fullPath: '/status/$hash';
      preLoaderRoute: typeof StatusHashImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/status/$hash': typeof StatusHashRoute;
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/status/$hash': typeof StatusHashRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/': typeof IndexRoute;
  '/status/$hash': typeof StatusHashRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/status/$hash';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/status/$hash';
  id: '__root__' | '/' | '/status/$hash';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  StatusHashRoute: typeof StatusHashRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StatusHashRoute: StatusHashRoute,
};

export const routeTree = rootRoute._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/status/$hash"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/status/$hash": {
      "filePath": "status.$hash.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
